[choreo]
# Choreo deployment configuration
name = "health-records-api"
description = "Health Records Management API"
version = "0.1.0"

[choreo.deployment]
# Deployment configuration
port = 9090
memory = "512Mi"
cpu = "0.5"

[choreo.environment]
# Railway MySQL Environment variables
DATABASE_URL = "mysql://root:ElBlPtqKfjEFfDBjcYzwfuqcTVTzEHCl@your-railway-private-domain:3306/railway?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true&maintainTimeStats=false&elideSetAutoCommits=true&useLocalSessionState=true"
DATABASE_HOST = "your-railway-private-domain"
DATABASE_PORT = "3306"
DATABASE_NAME = "railway"
DATABASE_USER = "root"
DATABASE_PASSWORD = "ElBlPtqKfjEFfDBjcYzwfuqcTVTzEHCl"

[choreo.health]
# Health check configuration
path = "/health"
port = 9090
initialDelaySeconds = 30
periodSeconds = 10
timeoutSeconds = 5
failureThreshold = 3
successThreshold = 1
