[database]
host = "mysql-production-8217.up.railway.app"
port = 3306
name = "railway"
user = "root"
password = "ElBlPtqKfjEFfDBjcYzwfuqcTVTzEHCl"

# JDBC URL for reference
url = "jdbc:mysql://mysql-production-8217.up.railway.app:3306/railway?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&autoReconnect=true"
